### ISSUE TITLE
Attributes are missing quotes around them

### ISSUE THREAD

**Issue by cbahiana** [tbela99/gzip#126]
Hi tbela99

I decided to give a go with GZIP at [https://www.pwabuilder.com/](https://www.pwabuilder.com/), which I had used before for another project.

Firstly the manifest file was not recognized. As I knew there had been a similar issue before [I opened a new issue on this](https://github.com/pwa-builder/PWABuilder/issues/1473).

There had actually been a problem with manifest parsing, but regardless of that, I also received an informing feed back: 

> Notice that all the attributes are missing quotes around them. In particular, you have this line:
> 
> `<link href=/manifest59f9eb28b0efc01bfce6b9b41877cb9d2322f142.json rel=manifest>`
> 
> It should be changed to:
> 
> `<link href="/manifest59f9eb28b0efc01bfce6b9b41877cb9d2322f142.json" rel="manifest">`

Now the manifest is being recognized, but not in its entirety. Options that were filled in the plugin are still not recognized (attachment).
![Screenshot from 2021-02-22 22-53-24](https://user-images.githubusercontent.com/6429519/108792789-e2f5c580-7560-11eb-9f92-43c1d86b3d68.png)

**Comment by tbela99** [comment]
unquoted attributes are perfectly valid with HTML5 https://dev.w3.org/html5/spec-LC/syntax.html#unquoted
If you want to check the manifest attributes, you can use your browser console. In this screenshot, I used firefox on github

![image](https://user-images.githubusercontent.com/58517/108793998-eeda8b00-7552-11eb-925b-0d2cb34edd13.png)

You should note that I may have not implemented support for all attributes because new attributes are added to the specs from time to time. The majority of the attributes listed in your screenshot are supported

**Comment by tbela99** [comment]
quotes are removed when you enable HTML minification and the page uses HTML5. Feel free to reopen this issue if you still have questions
